version: "3"

services:
  postgres:
    container_name: zbdihd-authservice-test-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "auth-service"
      MONGO_INITDB_ROOT_PASSWORD: "admin123"

    networks:
      - jenkins

networks:
  jenkins:
    external:
      name: jenkins
