version: "3"

services:
  postgres:
    container_name: tc-auth-service-tests-db
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: auth-service-tests
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: admin123
    networks:
      - jenkins

networks:
  jenkins:
    external:
      name: jenkins