version: "3"

services:
  api:
    container_name: zbdihd-authservice-api
    build:
      context: .
      dockerfile: production.deploy.Dockerfile
    depends_on:
      - mongo
    environment:
      VIRTUAL_HOST: api.zbdihd-authservice.quazarus.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: api.zbdihd-authservice.quazarus.com
      LETSENCRYPT_EMAIL: humberd.dev@gmail.com
      BUILD_NUMBER: ${BUILD_NO}
      COMMIT_HASH: ${COMMIT_HASH}
      ZBDIHD_AUTH_DATABASE_URL: ${ZBDIHD_AUTH_DATABASE_URL}
      ZBDIHD_AUTH_DATABASE_PORT: ${ZBDIHD_AUTH_DATABASE_PORT}
      ZBDIHD_AUTH_DATABASE_NAME: ${ZBDIHD_AUTH_DATABASE_NAME}
      ZBDIHD_AUTH_DATABASE_USERNAME: ${ZBDIHD_AUTH_DATABASE_USERNAME}
      ZBDIHD_AUTH_DATABASE_PASSWORD: ${ZBDIHD_AUTH_DATABASE_PASSWORD}
    networks:
      - nginx-proxy
      - db
    restart: always

  mongo:
    container_name: zbdihd-authservice-db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "auth-service"
      MONGO_INITDB_ROOT_PASSWORD: "admin123"
    volumes:
      - "dbdata:/data/db"
    networks:
      - db
    restart: always


networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  db:

volumes:
  dbdata: